/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SugestoesRouteImport } from './routes/sugestoes'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SocialRouteImport } from './routes/social'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const SugestoesRoute = SugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/social': typeof SocialRoute
  '/stats': typeof StatsRoute
  '/sugestoes': typeof SugestoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/social': typeof SocialRoute
  '/stats': typeof StatsRoute
  '/sugestoes': typeof SugestoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/social': typeof SocialRoute
  '/stats': typeof StatsRoute
  '/sugestoes': typeof SugestoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/notes' | '/social' | '/stats' | '/sugestoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/notes' | '/social' | '/stats' | '/sugestoes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notes'
    | '/social'
    | '/stats'
    | '/sugestoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  SocialRoute: typeof SocialRoute
  StatsRoute: typeof StatsRoute
  SugestoesRoute: typeof SugestoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sugestoes': {
      id: '/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof SugestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  SocialRoute: SocialRoute,
  StatsRoute: StatsRoute,
  SugestoesRoute: SugestoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
