// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdwbksfzwcawalordlrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkd2Jrc2Z6d2Nhd2Fsb3JkbHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MTIwNjksImV4cCI6MjA5NTM4ODA2OX0.JQQ9BtZBmdG6jrqtnw9omVC2UV-alwqpp-66Zuid2qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});